server:
  port: ${port:8300}

spring:
  application:
    name: food-consumer
  datasource:
    url: jdbc:mysql://localhost:3306/b2bgoods?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 666666

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000


thymeleaf:
  cache: false
  prefix: classpath:/templates/
feign:
  hystrix:
    enabled: true

