server:
  port: ${port:8200}

spring:
  application:
    name: food-provider
  datasource:
    url: jdbc:mysql://localhost:3306/b2bgoods?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 666666

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

mybatis:
  mapper-locations: classpath:/mapper/*

